name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup NPM
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000
          
      - name: Install Dependencies
        run: |
          npm cache clean --force
          npm install --no-optional --prefer-offline
          cd backend && npm cache clean --force && npm install --no-optional --prefer-offline
          
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}         # ← здесь должен быть 49.13.212.207
          username: ${{ secrets.SERVER_USERNAME }} # например, root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/mlm-project
            git pull origin main
            npm cache clean --force
            npm install --no-optional --prefer-offline
            cd backend
            npm cache clean --force
            npm install --no-optional --prefer-offline
            pm2 restart mlm-backend 